apiVersion: apps/v1
kind: Deployment
metadata:
  name: sops-converter-controller
  namespace: sops-converter
  labels:
    control-plane: sops-converter-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      control-plane: sops-converter-controller
  template:
    metadata:
      labels:
        control-plane: sops-converter-controller
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      serviceAccountName: sops-converter-controller
      containers:
      - command:
        - /manager
        name: sops-converter-controller
        image: ghcr.io/dhouti/sops-converter:v0.0.7
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
