apiVersion: apps/v1
kind: Deployment
metadata:
  name: sops-converter-controller
  namespace: sops-converter
spec:
  template:
    spec:
      containers:
      - name: sops-converter-controller
        envFrom:
        - secretRef:
           name: aws-creds
