apiVersion: secrets.dhouti.dev/v1beta1
kind: SopsSecret
metadata:
  name: test
  namespace: sopssecrets
data: |
  heck: ENC[AES256_GCM,data:59VK5VH+M50=,iv:0IDBiAicSBzAThh1izz0VdyCxNcjrxNlZAnZ55eqn+4=,tag:XHn1c1Ajxyt2LY996A0SLw==,type:str]
  test: ENC[AES256_GCM,data:mRPORhw=,iv:X58W/xQ1mDuuAl0iIqpkqB2y9tftnkMYp/Z382H4b8g=,tag:UR0qD5x2ncp/xEp01yGk8g==,type:str]
  idk_man: ENC[AES256_GCM,data:j6mY,iv:DDmhLx1Qb7uW2ItlZEGPJ7ByQ2JmuXBu6F8Wq17itQM=,tag:qjba5yxcP1H7t8FRxjvxfQ==,type:str]
  sops:
      kms:
      -   arn: arn:aws:kms:us-west-1:412278265988:key/e2064ff4-bc73-4d00-bbea-ba06bb896c49
          created_at: '2020-07-19T02:20:55Z'
          enc: AQICAHitntW+6X38rt1zS1CSPk61IctLonZ7CwI76ice7n/PdAE0/WMhlbFdh72NVUPN6nnlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdIMhXU/Eu7GgM9T/AgEQgDv2gnYFMkEi2KAtHH0DHMxs9BU2rDoY6DpM/9GQwRbSZtszqFUxSPn7Pj9FqTEvCczlJMr25jzClQ1yfA==
      gcp_kms: []
      azure_kv: []
      hc_vault: []
      lastmodified: '2020-07-19T02:20:55Z'
      mac: ENC[AES256_GCM,data:1EEbLDrmsp2dSfmoZclea+77Py/ANCGRsE+DQQOfV8XHIAcmn+5qpx2JBSJ4LWRVFJ4g0w30OweZFbQDCDi6EnkOruwg/p0AKUemLYzviq6AevdMGmKjZV4QPtwFyQymMTbbeuX4xcZY0Oo4SYdaY86iiVsKMTN7Jrx6tC7m518=,iv:0UDCtqJDxCv/ZkJDzx2wmp19j0PMdDs+ufNRkmM13tc=,tag:hFdR/i7KfWghkzJC8TfzNA==,type:str]
      pgp: []
      unencrypted_suffix: _unencrypted
      version: 3.6.0
