apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopssecrets-controller
  namespace: {{ .Values.Namespace }}
  labels:
    control-plane: sopssecrets-controller
spec:
  selector:
    matchLabels:
      control-plane: sopssecrets-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: sopssecrets-controller
    spec:
      serviceAccountName: sopssecrets-controller
      containers:
      - command:
        - /manager
        name: sopssecrets-controller
        image: dhouti/sops-converter:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
