apiVersion: v1
kind: ServiceAccount
metadata:
  name: sopssecrets-controller
  namespace: {{ .Values.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sopssecrets-controller
rules:
- apiGroups: [secrets.dhouti.dev]
  resources: [sopssecrets]
  verbs: ["*"]
- apiGroups: [secrets.dhouti.dev]
  resources: [sopssecrets/status]
  verbs: ["*"]
- apiGroups: [""]
  resources: [secrets]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sopsecrets-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sopssecrets-controller
subjects:
- kind: ServiceAccount
  name: sopssecrets-controller
  namespace: {{ .Values.Namespace }}
