apiVersion: v1
kind: ServiceAccount
metadata:
  name: sops-converter-controller
  namespace: sops-converter
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<IAM_ROLE_NAME>